Repository madhuakula/kubernetes-goat, pull requests merged in 2023-04, with the labels that each got.

#99 Fixed broken links
  guide/docs/getting-started.md
  guide/docs/how-to-run/aws-ec2-kind-cdk.md
  guide/docs/how-to-run/aws.md
  guide/docs/how-to-run/k3s.md
  guide/docs/how-to-run/kind.md
  guide/docs/how-to-run/kubernetes.md
Labels: bug

#100 fix borken links
  guide/docusaurus.config.js
  guide/package.json
Labels: bug

#101 Added Scenario-21 Cilium Tetragon - eBPF-based Security Observability and Runtime Enforcement
  README.md
  guide/docs/index.md
  guide/docs/scenarios/images/sc-21-1.png
  guide/docs/scenarios/images/sc-21-2.png
  guide/docs/scenarios/images/sc-21-3.png
  guide/docs/scenarios/images/sc-21-4.png
  guide/docs/scenarios/images/sc-21-5.png
  guide/docs/scenarios/images/scenario-21.png
  guide/docs/scenarios/scenario-21/index.md
  guide/docs/scenarios/scenario-21/scenario-21.md
  guide/docusaurus.config.js
  infrastructure/goat-home/home/content/scenario-21.md
Labels: documentation, enhancement, scenario

#102 updated the scenario-18 Falco overview image
  .DS_Store
  README.md
  guide/docs/index.md
  guide/docs/scenarios/images/scenario-18.png
  guide/docs/scenarios/scenario-18/scenario-18.md
  guide/docs/scenarios/scenario-21/scenario-21.md
Labels: documentation, enhancement

#103 Added Kyverno Policy Engine Security Hardening Scenario
  README.md
  guide/docs/index.md
  guide/docs/scenarios/images/sc-22-1.png
  guide/docs/scenarios/images/sc-22-2.png
  guide/docs/scenarios/images/sc-22-3.png
  guide/docs/scenarios/images/sc-22-4.png
  guide/docs/scenarios/images/sc-22-5.png
  guide/docs/scenarios/images/sc-22-6.png
  guide/docs/scenarios/images/scenario-22.png
  guide/docs/scenarios/scenario-22/index.md
  guide/docs/scenarios/scenario-22/scenario-22.md
  guide/docusaurus.config.js
  infrastructure/goat-home/home/content/scenario-22.md
  scenarios/kyverno-namespace-exec-block/kyverno-block-pod-exec-by-namespace.yaml
Labels: documentation, enhancement, scenario

#116 Support for Arm based Mac's - prevents system monitor (gotty) crash
  infrastructure/system-monitor/Dockerfile
Labels: bug
